<tbody @if(auth()->user()->hasRole('Admin')) wire:sortable="updateOrderLogOrder" @endif>
@foreach($order_logs as $key => $log)
    <tr wire:sortable.item="{{ $log->id }}" wire:key="order-{{ $log->id }}">
        <td>{{$log->row}}</td>
        <td @if(auth()->user()->hasRole('Admin'))wire:sortable.handle style="cursor: pointer" @endif>
            @if($log->status)
                @if($log->status == 'new')
                    Request Generated by AFL
                @elseif($log->status == 'accepted')
                    Request Accepted by 166
                @else
                    Order status changed to {{ $log->status }}
                @endif
            @endif
{{--            @if($log->driver_name)--}}
{{--                Driver Assigned: {{ $log->driver_name }}--}}
{{--            @endif--}}
            @if($log->driver_status)
                {{ $log->status_text }}
            @endif
        </td>
        <td>
            <a href="{{$log->driver_status_gps}}">{{Str::limit($log->driver_status_gps,50)}}</a>
        </td>
        <td>{{ $log->logged_at }}</td>
        <td>{{ $log->user }}</td>
        @if($log->driver_status && auth()->user()->hasRole('Admin'))
            <td>
                <button class="btn btn-warning" data-id="{{ $log->id }}"
                        type="button">Edit
                </button>
                <button class="btn btn-danger btn_danger" data-id="{{ $log->id }}"
                        type="button">Delete
                </button>

            </td>
        @endif
    </tr>
@endforeach
</tbody>
